language: python
python:
    - 2.7
install: 
    - echo 'Installing Dependencies'
    - python setup.py install
    - pip install -r requirements.txt --use-mirrors
    - pip install -r tests/requirements.txt --use-mirrors
    - pip install coveralls --use-mirrors
    - echo 'Dependencies Installed'
script:
    - coverage run --source=gh setup.py test
notifications:
  email: false
after_success:
  - coveralls  
